# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
      
         # Copy the 'post' folder
    - name: Push docs
      uses: azszero/docs@main
      with:
        source_file: '.' # Folder to copy
        destination_repo: 'azszero/www' # Target repo
        destination_folder: 'src/docs/' # Folder where to copy it
        user_email: 'xbaha@hotmail.com'
        user_name: 'xbaha'
        commit_message: "AUTO: Copying posts from Dom's to REBEL's website"
        git_server: 'github.com'
